@extends('layouts.app-support')
@push('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" type="text/css" href="{{ asset('newglobal/css/image-uploader.min.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.min.css" integrity="sha512-jU/7UFiaW5UBGODEopEqnbIAHOI8fO6T99m7Tsmqs2gkdujByJfkCbbfPSN4Wlqlb9TGnsuC0YgUgWkRBK7B9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<style>
    .fs-5{
        font-size: 11px;
    }
    .ul-widget2__username {
       font-size: 0.8rem;
    }
    button.write-message {
        margin-bottom: 30px;
    }
    .ul-widget3-body p {margin-bottom: 4px;}

    .loader {
        text-align: center;
        display: none;
    }

    .loader img {
        width: 30px;
    }
</style>
@endpush
@section('content')

<div class="breadcrumb row">
    <div class="col-md-6">
        <ul>
            <li><a href="#">Tickets</a></li>
            <li>Issue Reporting Tickets</li>
        </ul>
    </div>
</div>
<div class="separator-breadcrumb border-top"></div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="display table table-striped table-bordered" id="zero_configuration_table"
                        style="width:100%">
                        <thead>
                            <tr>
                                <th>Ticket#</th>
                                <th>FILE</th>
                                <th>Brand</th>
                                <th>Client</th>
                                <th>Generated By</th>
                                <th>Level</th>
                                <th>Status</th>
                                <th>Created On</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($issues as $issue)
                            <tr>
                                <td>{{ $issue->ticket_no }}</td>
                                <td>
                                <div class="image">
                                @if($issue->file_path == null)
                                        <p>No File</p>
                                    @else
                                        <a href="{{ $issue->generatePresignedUrl() }}" target="_blank" title="{{$issue->ticket_no}}.{{$issue->get_extension()}}">
                                        @if(($issue->get_extension() == 'jpg') || ($issue->get_extension() == 'png' ) || ($issue->get_extension() == 'webp' ) || ($issue->get_extension() == 'svg' ) || (($issue->get_extension() == 'jpeg')))
                                            <img src="{{ $issue->generatePresignedUrl() }}" alt="{{$issue->ticket_no}}" width="40">
                                        @else
                                            <p>{{ $issue->get_extension() }}</p>
                                        @endif
                                        </a>
                                    @endif
                                </div>
                                </td>
                                <td><button class="btn btn-secondary btn-sm">{{ $issue->brands->name }}</button></td>
                                <td><button class="btn btn-secondary btn-sm">{{ $issue->client->name }} {{ $issue->client->last_name }}</button></td>
                                <td><button class="btn btn-secondary btn-sm">{{ $issue->ticket_user->name }}</button> </td>
                                <td>
                                    @if($issue->level == 'Low')
                                        <span class="fs-5 btn btn-sm btn-default text-white">Low</span>
                                    @elseif($issue->level == 'High')
                                        <span class="fs-5 btn btn-sm btn-warning text-white">High</span>
                                    @elseif($issue->level == 'Critical')
                                        <span class="fs-5 btn btn-sm btn-danger text-white">Critical</span>
                                    @else
                                        <span class="fs-5 btn btn-sm btn-secondary text-white">Unknown</span>
                                    @endif
                                </td>
                                <td>
                                    @if($issue->status == 'Open')
                                        <span class="fs-5 btn btn-sm btn-danger text-white">Open</span>
                                    @elseif($issue->status == 'In Progress')
                                        <span class="fs-5 btn btn-sm btn-warning text-white">In Progress</span>
                                    @elseif($issue->status == 'Closed')
                                        <span class="fs-5 btn btn-sm btn-success text-white">Closed</span>
                                    @else
                                        <span class="fs-5 btn btn-sm btn-secondary text-white">Unknown</span>
                                    @endif
                                </td>

                                <td>
                                    <button class="btn btn-sm btn-secondary">{{ date('g:i a', strtotime($issue->created_at)) }}</button>
                                                <button class="btn btn-sm btn-secondary">{{ date('d M, Y', strtotime($issue->created_at)) }}</button>
                                </td>
                                <td>
                                    <a href="{{ route('support.issue.show', $issue->id) }}" class="btn btn-secondary btn-sm">View</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
